-- DO NOT EDIT THIS FILE. IT IS MANAGED BY THE SHELL AND FOLLOWS STRICT RULES
-- In other words, I ain't writing a lua parser for this, so please be a good boi/girl/whatever
hl.config({decoration={screen_shader="/home/r__idox/.config/quickshell/ii/services/hyprlandAntiFlashbangShader/anti-flashbang.glsl"}})
hl.config({debug={damage_tracking=1}})
