-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "20")

-- Settings
hl.config({
    general = {
        border_size = 0,
        extend_border_grab_area = 93,
        layout = "dwindle",
    },
})

-- Bezier curves
hl.curve("emphasizedDecel", { type = "bezier", points = { {0.05, 0.7}, {0.1, 1.0} } })

-- Animations
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 8.0,
    bezier = "default",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 3.0,
    bezier = "emphasizedDecel",
    style = "popin 80%",
})
